# Fusion Solar API response attributes
ATTR_AID_TYPE = 'aidType'
ATTR_BUILD_STATE = 'buildState'
ATTR_CAPACITY = 'capacity'
ATTR_COMBINE_TYPE = 'combineType'
ATTR_CONTACT_PERSON_PHONE = 'linkmanPho'
ATTR_DATA = 'data'
ATTR_DATA_COLLECT_TIME = 'collectTime'
ATTR_DATA_REALKPI = 'realKpi'
ATTR_DEVICE_ESN_CODE = 'esnCode'
ATTR_DEVICE_ID = 'id'
ATTR_DEVICE_INVERTER_TYPE = 'invType'
ATTR_DEVICE_LATITUDE = 'latitude'
ATTR_DEVICE_LONGITUDE = 'longitude'
ATTR_DEVICE_NAME = 'devName'
ATTR_DEVICE_SOFTWARE_VERSION = 'softwareVersion'
ATTR_DEVICE_STATION_CODE = 'stationCode'
ATTR_DEVICE_TYPE_ID = 'devTypeId'
ATTR_FAIL_CODE = 'failCode'
ATTR_LIST = 'list'
ATTR_MESSAGE = 'message'
ATTR_PARAMS = 'params'
ATTR_PARAMS_CURRENT_TIME = 'currentTime'
ATTR_PLANT_ADDRESS = 'plantAddress'
ATTR_PLANT_CODE = 'plantCode'
ATTR_PLANT_NAME = 'plantName'
ATTR_STATION_ADDRESS = 'stationAddr'
ATTR_STATION_CODE = 'stationCode'
ATTR_STATION_CONTACT_PERSON = 'contactPerson'
ATTR_STATION_LINKMAN = 'stationLinkman'
ATTR_STATION_NAME = 'stationName'
ATTR_SUCCESS = 'success'

# Data attributes
ATTR_REALTIME_POWER = 'realTimePower'
ATTR_TOTAL_CURRENT_DAY_ENERGY = 'dailyEnergy'
ATTR_TOTAL_CURRENT_MONTH_ENERGY = 'monthEnergy'
ATTR_TOTAL_CURRENT_YEAR_ENERGY = 'yearEnergy'
ATTR_TOTAL_LIFETIME_ENERGY = 'cumulativeEnergy'

ATTR_STATION_REAL_KPI_DATA_ITEM_MAP = 'dataItemMap'
ATTR_STATION_REAL_KPI_TOTAL_CURRENT_DAY_ENERGY = 'day_power'
ATTR_STATION_REAL_KPI_TOTAL_CURRENT_MONTH_ENERGY = 'month_power'
ATTR_STATION_REAL_KPI_TOTAL_LIFETIME_ENERGY = 'total_power'

ATTR_KPI_YEAR_INVERTER_POWER = 'inverter_power'

ATTR_DEVICE_REAL_KPI_ACTIVE_POWER = 'active_power'
ATTR_DEVICE_REAL_KPI_DATA_ITEM_MAP = 'dataItemMap'
ATTR_DEVICE_REAL_KPI_DEV_ID = 'devId'

PARAM_DEVICE_TYPE_ID_BATTERY = 39
PARAM_DEVICE_TYPE_ID_EMI = 10
PARAM_DEVICE_TYPE_ID_GRID_METER = 17
PARAM_DEVICE_TYPE_ID_POWER_SENSOR = 47
PARAM_DEVICE_TYPE_ID_RESIDENTIAL_INVERTER = 38
PARAM_DEVICE_TYPE_ID_C_I_UTILITY_ESS = 41
PARAM_DEVICE_TYPE_ID_STRING_INVERTER = 1
